name: '🔧 Global Dependencies'

runs:
    using: 'composite'
    steps:
        - name: 'Install Gloabal Dependecies'
          run: |
            sudo npm install -g --force npm@10.5.0 \
            browserslist@4.23.0 \
            typescript@5.4.3 \
            envsub@4.1.0 \
            dotenv@16.3.1 \
            dotenv-cli@7.4.1 \
            ts-node@10.9.2 \
            cross-env@7.0.3 \
            esbuild@0.20.2 \
            esbuild-node-externals@1.13.0 \
            esbuild-plugin-tsc@0.4.0 \
            npm-dts@1.3.12 \
            esbuild-plugin-d.ts@1.2.3
