name: '🔧 Global Dependencies'

runs:
    using: 'composite'
    steps:
        - name: 'Install Gloabal Dependecies'
          shell: bash
          run: |
            sudo -s &&
            npm install -g npm@10.5.0 &&
            npm install -g browserslist@4.23.0 &&
            npm install -g typescript@5.4.3 &&
            npm install -g envsub@4.1.0 &&
            npm install -g dotenv@16.3.1 &&
            npm install -g dotenv-cli@7.4.1 &&
            npm install -g ts-node@10.9.2 &&
            npm install -g cross-env@7.0.3 &&
            npm install -g esbuild@0.20.2 &&
            npm install -g esbuild-node-externals@1.13.0 &&
            npm install -g esbuild-plugin-tsc@0.4.0 &&
            npm install -g npm-dts@1.3.12
            npm install -g esbuild-plugin-d.ts@1.2.3
